apiVersion: v1
kind: Template
labels:
  template: nexus-iq-persistent-template
metadata:
  name: nexus-iq-persistent
  annotations:
    description: Sonatype Nexus IQ persistent template
    tags: ci,nexus-iq
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: ${SERVICE_NAME}
      spec:
        containers:
        - env:
          image: 'docker.io/sonatype/nexus-iq-server:${NEXUS_IQ_VERSION}'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8071
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 8070
            protocol: TCP
          - containerPort: 8071
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8071
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MAX_MEMORY}
            requests:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /sonatype-work
            name: ${SERVICE_NAME}-data
          - mountPath: /etc/nexus-iq-server
            name: ${SERVICE_NAME}-config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${SERVICE_NAME}-data
          persistentVolumeClaim:
            claimName: ${SERVICE_NAME}-pv
        - name: ${SERVICE_NAME}-config
          configMap:
            name: nexus-iq
            items:
            - key: config.yml
              path: config.yml
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: 8070-tcp
      port: 8070
      protocol: TCP
      targetPort: 8070
    - name: 8071-tcp
      port: 8071
      protocol: TCP
      targetPort: 8071
    selector:
      deploymentconfig: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    port:
      targetPort: 8070-tcp
    to:
      kind: Service
      name: ${SERVICE_NAME}
      weight: 100
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nexus-iq
  data:
    config.yml: |-
      ---
      sonatypeWork: "/sonatype-work"
      anonymousClientAccessAllowed: true
      server:
        applicationConnectors:
        - type: http
          port: 8070
        adminConnectors:
        - type: http
          port: 8071
        requestLog:
          appenders:
          - type: file
            currentLogFilename: "/var/log/nexus-iq-server/request.log"
            archivedLogFilenamePattern: "/var/log/nexus-iq-server/request-%d.log.gz"
            archivedFileCount: 5
      logging:
        level: DEBUG
        loggers:
          com.sonatype.insight.scan: INFO
          eu.medsea.mimeutil.MimeUtil2: INFO
          org.apache.http: INFO
          org.apache.http.wire: ERROR
          org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader: WARN
          org.eclipse.jetty: INFO
          org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter: INFO
        appenders:
        - type: console
          threshold: INFO
          logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger
            - %msg%n"
        - type: file
          threshold: ALL
          currentLogFilename: "/var/log/nexus-iq-server/clm-server.log"
          archivedLogFilenamePattern: "/var/log/nexus-iq-server/clm-server-%d.log.gz"
          logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger
            - %msg%n"
          archivedFileCount: 5
      createSampleData: true

parameters:
- displayName: Nexus IQ Service name
  name: SERVICE_NAME
  required: true
  value: nexus-iq
- displayName: Nexus IQ version
  name: NEXUS_IQ_VERSION
  required: true
  value: 1.47.0
- description: Volume space available for Sonatype Nexus e.g. 512Mi, 2Gi
  displayName: Volume Space for Nexus IQ
  name: VOLUME_CAPACITY
  required: true
  value: 4Gi
- description: Max memory allocated to the Nexus pod
  displayName: Max Memory
  name: MAX_MEMORY
  required: true
  value: 4Gi